mysql:
  enable: false
  host: "host"
  port: 3306
  database: "database"
  username: "root"
  password: ""
kit:
  armor: [DIAMOND_BOOTS, DIAMOND_LEGGINGS, DIAMOND_CHESTPLATE, DIAMOND_HELMET]
  inventory: [DIAMOND_SWORD]